FROM ubuntu:latest

MAINTAINER Anjaiah Methuku "anjaiahspr@gmail.com"

RUN apt-get update && apt-get install -y openjdk-8-jdk


WORKDIR /usr/local/bin/

ADD test-program.jar .

CMD ["java","-jar","test-program.jar"]
