FROM openjdk:8u131-jdk-alpine

MAINTAINER "Anjaiah Methuku"

RUN rm -rf /usr/local/tomcat/webapps/*

COPY ./target/fleetman-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

WORKDIR /usr/local/bin/

COPY ./target/fleetman-0.0.1-SNAPSHOT.jar webapp.jar

ENV JAVA_OPTS="-Dspring.profiles.active=docker-demo"
# Transfer our WAR
EXPOSE 8181
CMD ["java","-Dspring.profiles.active=docker-demo","-jar","webapp.jar"]
